import os
import re
import tempfile
import uuid

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

router = APIRouter()

EXPORT_DIR = os.path.join(tempfile.gettempdir(), "kalyx_exports")
os.makedirs(EXPORT_DIR, exist_ok=True)


def _safe_filename(name: str, ext: str) -> str:
    safe = re.sub(r'[<>:"/\\|?*]', "", name or "course").strip() or "course"
    safe = safe[:80]
    return f"{safe}_KALYX.{ext}"


class ExportRequest(BaseModel):
    course: str
    slides: list
    notes: list
    quiz: list
    bloom_coverage: dict


@router.post("/api/export/pdf")
async def export_pdf(request: ExportRequest):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import (
            SimpleDocTemplate,
            Paragraph,
            Spacer,
            PageBreak,
        )
        from reportlab.lib.units import inch

        filename = f"kalyx_{uuid.uuid4().hex[:8]}.pdf"
        filepath = os.path.join(EXPORT_DIR, filename)

        doc = SimpleDocTemplate(
            filepath,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50,
        )

        styles = getSampleStyleSheet()

        navy = HexColor("#0D1B2A")
        blue = HexColor("#0EA5E9")
        grey = HexColor("#475569")

        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Title"],
            fontSize=28,
            textColor=navy,
            spaceAfter=20,
            fontName="Helvetica-Bold",
        )

        heading_style = ParagraphStyle(
            "CustomHeading",
            parent=styles["Heading1"],
            fontSize=16,
            textColor=blue,
            spaceAfter=10,
            fontName="Helvetica-Bold",
        )

        subheading_style = ParagraphStyle(
            "CustomSubHeading",
            parent=styles["Heading2"],
            fontSize=13,
            textColor=navy,
            spaceAfter=8,
            fontName="Helvetica-Bold",
        )

        body_style = ParagraphStyle(
            "CustomBody",
            parent=styles["Normal"],
            fontSize=11,
            textColor=grey,
            spaceAfter=6,
            leading=16,
            fontName="Helvetica",
        )

        bullet_style = ParagraphStyle(
            "CustomBullet",
            parent=styles["Normal"],
            fontSize=10,
            textColor=grey,
            spaceAfter=4,
            leftIndent=20,
            fontName="Helvetica",
        )

        def esc(text):
            if not text:
                return ""
            return (
                str(text)
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )

        story = []

        story.append(Paragraph(esc(request.course), title_style))
        story.append(
            Paragraph(
                "Generated by KALYX — AI Course Content Generator",
                body_style,
            )
        )
        story.append(Paragraph("Debug Devils | SRMIST", body_style))
        story.append(Spacer(1, 30))

        story.append(Paragraph("SLIDES", heading_style))
        story.append(Spacer(1, 10))

        for slide in request.slides:
            story.append(
                Paragraph(
                    esc(
                        f"Slide {slide.get('slide_number', '')}: {slide.get('title', '')}"
                    ),
                    subheading_style,
                )
            )

            for bullet in slide.get("bullets", []):
                story.append(Paragraph(f"• {esc(bullet)}", bullet_style))

            if slide.get("key_takeaway"):
                story.append(
                    Paragraph(
                        f"Key Takeaway: {esc(slide.get('key_takeaway'))}",
                        body_style,
                    )
                )
            story.append(Spacer(1, 12))

        story.append(PageBreak())
        story.append(Paragraph("LECTURE NOTES", heading_style))
        story.append(Spacer(1, 10))

        for note in request.notes:
            story.append(Paragraph(esc(note.get("topic", "")), subheading_style))

            for field in [
                "introduction",
                "core_concepts",
                "deep_explanation",
                "real_world_application",
                "common_mistakes",
                "summary",
            ]:
                if note.get(field):
                    story.append(Paragraph(esc(note.get(field, "")), body_style))
                    story.append(Spacer(1, 6))

            story.append(Spacer(1, 15))

        story.append(PageBreak())
        story.append(Paragraph("QUIZ QUESTIONS", heading_style))
        story.append(Spacer(1, 10))

        for q in request.quiz:
            story.append(
                Paragraph(
                    esc(
                        f"Q{q.get('question_number', '')}: {q.get('question', '')}"
                    ),
                    subheading_style,
                )
            )
            story.append(
                Paragraph(
                    esc(f"Bloom's Level: {q.get('bloom_level', '')}"),
                    body_style,
                )
            )

            for opt in q.get("options", []):
                marker = "✓" if opt == q.get("answer") else "○"
                story.append(Paragraph(f"{marker} {esc(opt)}", bullet_style))

            if q.get("explanation"):
                story.append(
                    Paragraph(
                        f"Explanation: {esc(q.get('explanation'))}",
                        body_style,
                    )
                )
            story.append(Spacer(1, 12))

        doc.build(story)

        return FileResponse(
            filepath,
            media_type="application/pdf",
            filename=_safe_filename(request.course, "pdf"),
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) from e


@router.post("/api/export/pptx")
async def export_pptx(request: ExportRequest):
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN

        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        blank_layout = prs.slide_layouts[6]

        def hex_to_rgb(hex_color):
            hex_color = hex_color.lstrip("#")
            return RGBColor(
                int(hex_color[0:2], 16),
                int(hex_color[2:4], 16),
                int(hex_color[4:6], 16),
            )

        navy = hex_to_rgb("0D1B2A")
        blue = hex_to_rgb("0EA5E9")
        white = hex_to_rgb("FFFFFF")
        light_grey = hex_to_rgb("CBD5E1")

        title_slide = prs.slides.add_slide(blank_layout)

        bg = title_slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = navy

        title_box = title_slide.shapes.add_textbox(
            Inches(1), Inches(2.5), Inches(11), Inches(1.5)
        )
        title_frame = title_box.text_frame
        title_para = title_frame.paragraphs[0]
        title_para.alignment = PP_ALIGN.CENTER
        title_run = title_para.add_run()
        title_run.text = request.course
        title_run.font.size = Pt(44)
        title_run.font.bold = True
        title_run.font.color.rgb = white

        sub_box = title_slide.shapes.add_textbox(
            Inches(1), Inches(4.2), Inches(11), Inches(0.8)
        )
        sub_frame = sub_box.text_frame
        sub_para = sub_frame.paragraphs[0]
        sub_para.alignment = PP_ALIGN.CENTER
        sub_run = sub_para.add_run()
        sub_run.text = "Generated by KALYX — Debug Devils | SRMIST"
        sub_run.font.size = Pt(18)
        sub_run.font.color.rgb = blue

        for slide_data in request.slides:
            slide = prs.slides.add_slide(blank_layout)

            bg = slide.background
            fill = bg.fill
            fill.solid()
            fill.fore_color.rgb = navy

            accent = slide.shapes.add_shape(
                1,
                Inches(0),
                Inches(0),
                Inches(0.15),
                Inches(7.5),
            )
            accent.fill.solid()
            accent.fill.fore_color.rgb = blue
            accent.line.fill.background()

            title_box = slide.shapes.add_textbox(
                Inches(0.4), Inches(0.3), Inches(11), Inches(0.9)
            )
            tf = title_box.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            run = p.add_run()
            run.text = slide_data.get("title", "")
            run.font.size = Pt(24)
            run.font.bold = True
            run.font.color.rgb = white

            unit_box = slide.shapes.add_textbox(
                Inches(10.5), Inches(0.3), Inches(2.5), Inches(0.4)
            )
            uf = unit_box.text_frame
            up = uf.paragraphs[0]
            up.alignment = PP_ALIGN.RIGHT
            ur = up.add_run()
            ur.text = slide_data.get("unit", "")
            ur.font.size = Pt(10)
            ur.font.color.rgb = blue

            content_box = slide.shapes.add_textbox(
                Inches(0.4), Inches(1.3), Inches(12.5), Inches(5.2)
            )
            cf = content_box.text_frame
            cf.word_wrap = True

            bullets = slide_data.get("bullets", [])
            for i, bullet in enumerate(bullets[:8]):
                if i == 0:
                    p = cf.paragraphs[0]
                else:
                    p = cf.add_paragraph()
                p.level = 0
                run = p.add_run()
                run.text = f"▸  {bullet}"
                run.font.size = Pt(13)
                run.font.color.rgb = light_grey
                p.space_after = Pt(6)

            if slide_data.get("key_takeaway"):
                p = cf.add_paragraph()
                p.space_before = Pt(10)
                run = p.add_run()
                run.text = f"💡 {slide_data.get('key_takeaway')}"
                run.font.size = Pt(12)
                run.font.italic = True
                run.font.color.rgb = blue

        filename = f"kalyx_{uuid.uuid4().hex[:8]}.pptx"
        filepath = os.path.join(EXPORT_DIR, filename)
        prs.save(filepath)

        return FileResponse(
            filepath,
            media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
            filename=_safe_filename(request.course, "pptx"),
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e)) from e
